name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the appropriate Node.js version
          cache: "yarn"

      - name: Check yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn install # Use npm install if you prefer npm

      - name: Build project
        run: yarn run build # Adjust the build command as needed

      - name: Archive artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/ # Adjust this to the path of your build output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: github-pages
          path: ./dist/ # The same path you used in the build step

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
